---
title: "[PoC] Use async with the savvy framework"
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

This repository is an experiment to use ALTREP to wrap async with the power of my [savvy framework](https://github.com/yutannihilation/savvy).

<!-- badges: start -->
<!-- badges: end -->

## Implementation

This function returns `c(1L, 2L, 3L)` after sleeping for 3 seconds.

``` rust
async fn vec_i32_async() -> Vec<i32> {
    async {
        Timer::after(std::time::Duration::from_secs(3)).await;
        vec![1, 2, 3]
    }
    .await
}

// ...snip...

#[savvy]
fn sleepy_vec() -> savvy::Result<savvy::Sexp> {
    let f = vec_i32_async();
    SleepyVec {
        future: Box::pin(f),
        result: None,
    }
    .into_altrep()
}
```

## Behavior

```{r example}
library(savvyAsyncPoC)

x <- sleepy_vec()

# While I'm waiting for 1 second, the task is executed in background.
Sys.sleep(1)

# It takes 3 seconds to finish the task, and 1 second has passed.
# So, this should take about 2 seconds.
system.time(x[1])

# After that, the result is cached.
system.time(sum(x))
```

